In [1]:
# pip install walkscore-api

Requirement already satisfied: walkscore-api in /Users/carl/opt/anaconda3/lib/python3.9/site-packages (1.0.1)
Requirement already satisfied: validator-collection>=1.3.0 in /Users/carl/opt/anaconda3/lib/python3.9/site-packages (from walkscore-api) (1.5.0)
Requirement already satisfied: backoff-utils>=1.0.0 in /Users/carl/opt/anaconda3/lib/python3.9/site-packages (from walkscore-api) (1.0.1)
Requirement already satisfied: jsonschema in /Users/carl/opt/anaconda3/lib/python3.9/site-packages (from validator-collection>=1.3.0->walkscore-api) (4.16.0)
Requirement already satisfied: attrs>=17.4.0 in /Users/carl/opt/anaconda3/lib/python3.9/site-packages (from jsonschema->validator-collection>=1.3.0->walkscore-api) (21.4.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /Users/carl/opt/anaconda3/lib/python3.9/site-packages (from jsonschema->validator-collection>=1.3.0->walkscore-api) (0.18.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
from walkscore import WalkScoreAPI

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [57]:
df = pd.read_csv('../data/mergedAPI2.csv')
df.head(2)

,id,latitude,longitude,price,shared_status,accommodates,accomodation_group,bathrooms,bedrooms,beds_adjusted,neighborhood,has_neighborhood_overview,has_reviews,listing_url,host_in_CO,host_lives_in_neighborhood,host_id,host_name,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,host_total_listings_count,host_has_profile_pic,host_identity_verified,has_host_about,years_hosting,years_of_reviews,license_listed,response_time,host_lives_in_neighborhood.1,name,host_about,description,neighborhood_overview,amenities,minimum_nights,maximum_nights,min_stay_group,max_stay_group,has_availability,instant_bookable,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month,bike_scores,walk_scores,property_page_links,transit_scores
0,177,39.69551,-104.92489,$79.00,entire home,2,0-2,1.0,1.0,1.0,Virginia Village,1,1,https://www.airbnb.com/rooms/177,1,1,615,Joe,within an hour,1.0,1.00,1.0,Virginia Village,2.0,2.0,1.0,0.0,1,15.0,6.0,1,0.0,1,Tiny Home in the Heart of the City- ECO FRIENDLY,"I'm originally from Oklahoma, but have lived i...","160 sq ft + 80 sq ft loft for sleeping, Sleeps...","Quiet neighborhood next to park, creeks and bi...","[""Hot water"", ""Long term stays allowed"", ""Coff...",29,400,month,long_term,1,0,120,24,0,4.85,4.96,4.89,4.97,4.94,4.85,4.78,1.56,84.0,51.0,https://www.walkscore.com/score/loc/lat=39.695...,37.0
1,360,39.76758,-105.00316,$133.00,entire home,3,3-4,1.0,2.0,2.0,Highland,1,1,https://www.airbnb.com/rooms/360,1,1,666,Jennifer & Giovanni,within an hour,1.0,0.87,1.0,Highland,4.0,4.0,1.0,1.0,1,15.0,4.0,1,0.0,1,Sit in the Peaceful Garden of the Chickadee Co...,We are artists and tinkerers.\r\n \r\nWe enjoy...,Enjoy the famous Colorado weather and unplug i...,The cottage is located in the center of Lower ...,"[""Coffee maker"", ""Washer"", ""Bedroom comforts"",...",29,35,month,2_months,1,0,174,7,1,4.99,4.99,4.96,5.00,5.00,5.00,4.91,3.26,93.0,90.0,https://www.walkscore.com/score/loc/lat=39.767...,49.0

In [58]:
df.shape

(5249, 59)

In [5]:
df.isna().sum()

id                                 0
latitude                           0
longitude                          0
price                              0
shared_status                      0
accommodates                       0
accomodation_group                 0
bathrooms                          0
bedrooms                           0
beds_adjusted                      0
neighborhood                       0
city                               0
has_neighborhood_overview          0
has_reviews                        0
host_in_CO                         0
host_lives_in_neighborhood         0
host_id                            0
host_name                          0
host_response_time               727
host_response_rate               727
host_acceptance_rate             423
host_is_superhost                  0
host_neighbourhood               294
host_listings_count                0
host_total_listings_count          0
host_has_profile_pic               0
host_identity_verified             0
has_host_about                     0
years_hosting                      0
years_of_reviews                   0
license_listed                     0
response_time                      0
host_lives_in_neighborhood.1       0
name                               0
host_about                      1973
description                       21
neighborhood_overview           1497
amenities                          0
minimum_nights                     0
maximum_nights                     0
min_stay_group                     0
max_stay_group                     0
has_availability                   0
availability_30                    0
availability_60                    0
availability_90                    0
availability_365                   0
instant_bookable                   0
number_of_reviews                  0
number_of_reviews_ltm              0
number_of_reviews_l30d             0
review_scores_rating             885
review_scores_accuracy           889
review_scores_cleanliness        889
review_scores_checkin            889
review_scores_communication      889
review_scores_location           889
review_scores_value              889
reviews_per_month                885
bike_scores                        0
walk_scores                        0
transit_scores                  4030
property_page_links                0
25*k                               0
dtype: int64

In [6]:
missingtransit=df[df['transit_scores'].isna()]

In [47]:
transitscores=df[df['transit_scores'].notna()]

In [48]:
transitscores.shape

(1179, 64)

In [15]:
missingtransit.shape

(4030, 64)

In [23]:
missingtransit= missingtransit.drop('transit_scores', axis=1)

In [24]:
missingtransit.shape

(4030, 63)

In [25]:
missing1=missingtransit.iloc[0:700, :]
missing2=missingtransit.iloc[701:1600, :]
missing3=missingtransit.iloc[1601:2500, :]
missing4=missingtransit.iloc[2501:3400, :]
missing5=missingtransit.iloc[3401: , :]

In [26]:
missing5.shape

(629, 63)

In [21]:
api_key = 'bfbd763410626e5d278b9430e7d89c3e'

walkscore_api = WalkScoreAPI(api_key = api_key)

# testing on one location

In [10]:
result = walkscore_api.get_score(latitude = 39.69551, longitude = -104.92489, return_transit_score=True)

# the WalkScore for the location
result.walk_score

51

In [11]:
result.walk_description

'Somewhat Walkable'

In [12]:
# the TransitScore for the location
result.transit_score

#according to forums online, the transit score isn't included with the stanard API...

37

In [ ]:
# the BikeScore for the location
result.bike_score

# Missing1 API loop
help from Katie Sylvia

In [27]:
# Extract the latitude and longitude values
latitudes = missing1['latitude']
longitudes = missing1['longitude']

# Make API requests to get the walk scores, bike scores, and property page links
results = []
for lat, long in zip(latitudes, longitudes):
    result = walkscore_api.get_score(latitude=lat, longitude=long, return_transit_score=True)
    results.append(result)

# Extract the bike scores, walk scores, and property page links from the results
bike_scores = [result.bike_score for result in results]
walk_scores = [result.walk_score for result in results]
property_page_links = [result.property_page_link for result in results]
transit_scores = [result.transit_score for result in results]

# Add the bike scores, walk scores, and property page links to the corresponding rows of the dataframe
# df['bike_scores'] = bike_scores
# df['walk_scores'] = walk_scores
missing1['transit_scores'] = transit_scores
# df['property_page_links'] = property_page_links

/var/folders/f5/d5gp33rs3pj8ngm1m9by8vn80000gn/T/ipykernel_79916/3308797602.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  missing1['transit_scores'] = transit_scores

In [29]:
missing1.head()

,id,latitude,longitude,price,shared_status,accommodates,accomodation_group,bathrooms,bedrooms,beds_adjusted,neighborhood,city,has_neighborhood_overview,has_reviews,host_in_CO,host_lives_in_neighborhood,host_id,host_name,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,host_total_listings_count,host_has_profile_pic,host_identity_verified,has_host_about,years_hosting,years_of_reviews,license_listed,response_time,host_lives_in_neighborhood.1,name,host_about,description,neighborhood_overview,amenities,minimum_nights,maximum_nights,min_stay_group,max_stay_group,has_availability,availability_30,availability_60,availability_90,availability_365,instant_bookable,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month,bike_scores,walk_scores,property_page_links,25*k,transit_scores
528,15125534,39.69714,-104.92788,69.0,entire home,2,0-2,1.0,1.0,1.0,Washington Virginia Vale,Denver,0,1,1,0,5910663,Tony,within an hour,1.0,0.96,1.0,Lincoln Park,3.0,5.0,1.0,1.0,1,10.0,6.0,0,0.0,0,Cherry Creek Studio Apt,"Born and raised in Denver, where I work in non...",Small Studio Condo right off the Cherry Creek ...,NaN,"[""Hot water"", ""Long term stays allowed"", ""Free...",29,1125,month,long_term,1,30,60,90,365,0,28,1,0,4.75,4.79,4.75,4.92,5.00,4.84,4.52,0.37,85.0,24.0,https://www.walkscore.com/score/loc/lat=39.697...,3.0,NaN
1037,25476150,39.76437,-104.98015,224.0,entire home,3,3-4,1.5,1.0,3.0,Five Points,Denver,1,1,1,1,32622027,Nada,within a day,0.9,0.95,0.0,Five Points,3.0,3.0,1.0,1.0,0,8.0,4.0,1,2.0,1,Urban Oasis - RiNo Art District,NaN,Welcome hOMe to the Urban Oasis featuring mode...,"Nicknamed “RiNo,” the trendy River North Art D...","[""Hot water"", ""Coffee maker"", ""Washer"", ""Oven""...",3,21,weekend,month,1,21,49,75,348,0,135,38,1,4.99,4.99,4.98,4.96,4.98,4.99,4.80,2.44,98.0,92.0,https://www.walkscore.com/score/loc/lat=39.764...,9.0,58.0
1038,27663042,39.78205,-104.73806,40.0,private room,2,0-2,1.0,1.0,1.0,Gateway - Green Valley Ranch,Denver,0,1,1,0,208115656,Bekele,within a few hours,1.0,0.86,0.0,Gateway / Green Valley Ranch,2.0,3.0,1.0,1.0,0,5.0,4.0,1,1.0,0,Studio on the first floor of the main house,NaN,This is a separate room that you enter through...,NaN,"[""First aid kit"", ""Private entrance"", ""Long te...",29,1111,month,long_term,1,29,59,89,89,0,18,4,0,4.78,4.89,4.89,4.89,5.00,5.00,4.78,0.34,51.0,5.0,https://www.walkscore.com/score/loc/lat=39.782...,2.0,32.0
1039,27696005,39.67421,-105.04865,101.0,entire home,4,3-4,2.0,2.0,2.0,Harvey Park,Denver,1,1,1,1,160654043,Jim,within an hour,1.0,0.82,0.0,Harvey Park,4.0,5.0,1.0,1.0,1,6.0,4.0,1,0.0,1,Denver/Lakewood House with private yard/patio,I've been living in Denver for nearly 20 years...,Cozy home in quiet suburban neighborhood. Pri...,Quiet neighborhood with shopping and restauran...,"[""Hot water"", ""Long term stays allowed"", ""Coff...",3,31,weekend,2_months,1,25,55,85,85,1,73,5,1,4.92,4.95,4.96,4.97,5.00,4.88,4.93,1.38,60.0,38.0,https://www.walkscore.com/score/loc/lat=39.674...,5.0,37.0
1040,25476793,39.76362,-104.96994,147.0,entire home,2,0-2,1.0,1.0,1.0,Cole,Denver,1,1,1,1,19196235,Mike,within an hour,1.0,1.00,1.0,Cole,1.0,1.0,1.0,0.0,1,9.0,4.0,1,0.0,1,Private Entry Suite in Cole/RiNo Near Downtown,Mike and Bryan here! We’ve been married for 9 ...,"Contemporary and comfortable, this historic ho...",Easily access all that Denver has to offer! If...,"[""Hot water"", ""Long term stays allowed"", ""Coff...",2,29,weekend,month,1,26,56,86,166,0,323,71,5,5.00,5.00,4.98,5.00,4.99,4.92,4.95,5.82,98.0,89.0,https://www.walkscore.com/score/loc/lat=39.763...,6.0,58.0

In [30]:
missing1.shape

(700, 64)

In [31]:
missing1['bike_scores'].isna().sum()

0

In [32]:
missing1['walk_scores'].isna().sum()

0

In [42]:
#why are there still missings??  This transit score is such a pain.  

missing1['transit_scores'].isna().sum()

77

In [74]:
# missing1.to_csv('../data/missing1.csv', index=False)

In [49]:
added1= pd.concat([transitscores, missing1], ignore_index=True)

In [50]:
added1.shape

(1879, 64)

In [51]:
added1.isna().sum()

id                                0
latitude                          0
longitude                         0
price                             0
shared_status                     0
accommodates                      0
accomodation_group                0
bathrooms                         0
bedrooms                          0
beds_adjusted                     0
neighborhood                      0
city                              0
has_neighborhood_overview         0
has_reviews                       0
host_in_CO                        0
host_lives_in_neighborhood        0
host_id                           0
host_name                         0
host_response_time              377
host_response_rate              377
host_acceptance_rate            224
host_is_superhost                 0
host_neighbourhood              204
host_listings_count               0
host_total_listings_count         0
host_has_profile_pic              0
host_identity_verified            0
has_host_about                    0
years_hosting                     0
years_of_reviews                  0
license_listed                    0
response_time                     0
host_lives_in_neighborhood.1      0
name                              0
host_about                      524
description                       7
neighborhood_overview           271
amenities                         0
minimum_nights                    0
maximum_nights                    0
min_stay_group                    0
max_stay_group                    0
has_availability                  0
availability_30                   0
availability_60                   0
availability_90                   0
availability_365                  0
instant_bookable                  0
number_of_reviews                 0
number_of_reviews_ltm             0
number_of_reviews_l30d            0
review_scores_rating             75
review_scores_accuracy           79
review_scores_cleanliness        79
review_scores_checkin            79
review_scores_communication      79
review_scores_location           79
review_scores_value              79
reviews_per_month                75
bike_scores                       0
walk_scores                       0
transit_scores                   77
property_page_links               0
25*k                              0
dtype: int64

In [70]:
added1.to_csv('../data/added1.csv', index=False)

In [52]:
# added1.to_csv('../data/building_transit_api.csv', index=False)

# creating an api df

In [127]:

api=df[['id', 'latitude', 'longitude','bike_scores', 'walk_scores', 'transit_scores', 'property_page_links']]

In [42]:
api.head()

,id,latitude,longitude,bike_scores,walk_scores,transit_scores,property_page_links
0,177,39.69551,-104.92489,84,51,37.0,https://www.walkscore.com/score/loc/lat=39.695...
1,360,39.76758,-105.00316,93,90,49.0,https://www.walkscore.com/score/loc/lat=39.767...
2,2361919,39.77960,-105.03859,76,81,34.0,https://www.walkscore.com/score/loc/lat=39.779...
3,2386289,39.76777,-105.03529,75,86,39.0,https://www.walkscore.com/score/loc/lat=39.767...
4,4992412,39.76822,-105.00249,93,90,49.0,https://www.walkscore.com/score/loc/lat=39.768...

In [60]:
# api.to_csv('../data/all_api.csv', index=False)

(5050, 7)

In [185]:
api.isna().sum()

id                        0
latitude                  0
longitude                 0
bike_scores               0
walk_scores               0
transit_scores         4051
property_page_links       0
dtype: int64

In [ ]:
# df.to_csv('../data/allAPI.csv', index=False)

In [59]:
# allAPI = pd.read_csv('../data/building_transit_api.csv')
allAPI.shape

(1879, 64)

# Missing 2

In [62]:
# Extract the latitude and longitude values
latitudes = missing2['latitude']
longitudes = missing2['longitude']

# Make API requests to get the walk scores, bike scores, and property page links
results = []
for lat, long in zip(latitudes, longitudes):
    result = walkscore_api.get_score(latitude=lat, longitude=long, return_transit_score=True)
    results.append(result)

# Extract the bike scores, walk scores, and property page links from the results
bike_scores = [result.bike_score for result in results]
walk_scores = [result.walk_score for result in results]
property_page_links = [result.property_page_link for result in results]
transit_scores = [result.transit_score for result in results]

# Add the bike scores, walk scores, and property page links to the corresponding rows of the dataframe
# df['bike_scores'] = bike_scores
# df['walk_scores'] = walk_scores
missing2['transit_scores'] = transit_scores
# df['property_page_links'] = property_page_links

/var/folders/f5/d5gp33rs3pj8ngm1m9by8vn80000gn/T/ipykernel_79916/769394944.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  missing2['transit_scores'] = transit_scores

In [63]:
missing2.head()

,id,latitude,longitude,price,shared_status,accommodates,accomodation_group,bathrooms,bedrooms,beds_adjusted,neighborhood,city,has_neighborhood_overview,has_reviews,host_in_CO,host_lives_in_neighborhood,host_id,host_name,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,host_total_listings_count,host_has_profile_pic,host_identity_verified,has_host_about,years_hosting,years_of_reviews,license_listed,response_time,host_lives_in_neighborhood.1,name,host_about,description,neighborhood_overview,amenities,minimum_nights,maximum_nights,min_stay_group,max_stay_group,has_availability,availability_30,availability_60,availability_90,availability_365,instant_bookable,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month,bike_scores,walk_scores,property_page_links,25*k,transit_scores
1761,40890051,39.74330,-105.03627,78.0,entire home,3,3-4,1.0,1.0,1.0,West Colfax,Denver,1,1,1,1,52023990,Nick,within an hour,1.0,0.98,1.0,West Colfax,1.0,1.0,1.0,1.0,1,8.0,3.0,1,0.0,1,Private and Spacious Suite | 10 min from Downtown,"I Love to travel, explore the outdoors and exp...",** Extra deep cleaning and CDC approved disinf...,*Vibrant and highly desirable Sloan’s Lake/Hig...,"[""Cleaning products"", ""Hot water"", ""Fast wifi ...",3,6,weekend,week,1,9,33,62,62,0,107,28,0,4.91,4.92,4.95,4.99,4.98,4.97,4.81,2.92,95.0,75.0,https://www.walkscore.com/score/loc/lat=39.743...,4.0,48.0
1762,42778407,39.76257,-105.01100,129.0,entire home,2,0-2,1.0,1.0,1.0,Highland,Denver,1,1,1,1,30985892,Addison,NaN,NaN,1.00,1.0,Highland,1.0,1.0,1.0,1.0,0,8.0,0.0,0,4.0,1,"**New** Stylish LoHi Escape- Walkable, Fast WiFi",NaN,"This luxurious one bedroom unit, in the heart ...","LoHi, just off of downtown, is the local hot s...","[""Long term stays allowed"", ""Coffee maker"", ""W...",29,1125,month,long_term,1,1,1,1,58,0,5,5,0,5.00,5.00,5.00,5.00,5.00,5.00,5.00,0.43,87.0,94.0,https://www.walkscore.com/score/loc/lat=39.762...,6.0,68.0
1764,41982230,39.73521,-104.91843,115.0,entire home,4,3-4,1.0,2.0,2.0,Montclair,Denver,1,1,1,0,134744962,Vicky,within a day,1.0,0.50,0.0,East,1.0,3.0,1.0,1.0,1,6.0,0.0,1,2.0,0,Cozy mid-century mod bungalow in central location,"Hi! I'm a Belgian native, and I've been living...",Stylish cozy 1950s bungalow with updated ameni...,Mayfair/Montclair neighborhood. Mainly family ...,"[""Cleaning products"", ""Hot water"", ""Long term ...",3,360,weekend,year,1,0,18,36,103,0,1,0,0,5.00,5.00,5.00,5.00,5.00,5.00,5.00,0.03,79.0,71.0,https://www.walkscore.com/score/loc/lat=39.735...,5.0,49.0
1765,42024030,39.75348,-104.91422,100.0,entire home,3,3-4,1.0,1.0,2.0,North Park Hill,Denver,1,1,1,0,333038216,The Phoenix,NaN,NaN,1.00,1.0,Northeast,1.0,2.0,1.0,1.0,1,3.0,2.0,1,4.0,0,Cozy Basement Apartment,Enjoy the Mile High City in our Cozy and Clean...,"Beautiful yet quiet Park Hill neighborhood, cl...",Safe and walkable area. Park Hill area that i...,"[""Cleaning products"", ""Hot water"", ""Long term ...",29,29,month,month,1,0,0,0,0,1,58,5,0,4.83,4.91,4.83,4.90,4.93,4.91,4.83,1.91,83.0,64.0,https://www.walkscore.com/score/loc/lat=39.753...,5.0,40.0
1766,42790978,39.77839,-105.04357,205.0,entire home,4,3-4,1.0,2.0,2.0,Berkeley,Denver,1,1,1,0,24616866,Allison,within an hour,1.0,0.93,1.0,Northwest,1.0,2.0,1.0,1.0,1,9.0,2.0,1,0.0,0,Light Filled Tennyson Hideaway,I'm an East Coast transplant who's been strugg...,Welcome to our quiet little corner in the popu...,"Tennyson Street, in Denver’s historic Berkeley...","[""Hot water"", ""Long term stays allowed"", ""Coff...",2,30,weekend,month,1,20,50,80,349,0,52,18,0,4.94,4.98,5.00,5.00,5.00,4.90,4.90,1.55,72.0,91.0,https://www.walkscore.com/score/loc/lat=39.778...,9.0,32.0

In [64]:
missing2.shape

(899, 64)

In [65]:
missing2['bike_scores'].isna().sum()

0

In [66]:
missing2['walk_scores'].isna().sum()

0

In [67]:
#why are there still missings??  This transit score is such a pain.  

missing2['transit_scores'].isna().sum()

1

In [75]:
# missing2.to_csv('../data/missing2.csv', index=False)

In [71]:
added2= pd.concat([added1, missing2], ignore_index=True)

In [72]:
added2.shape

(2778, 64)

In [51]:
added2.isna().sum()

id                                0
latitude                          0
longitude                         0
price                             0
shared_status                     0
accommodates                      0
accomodation_group                0
bathrooms                         0
bedrooms                          0
beds_adjusted                     0
neighborhood                      0
city                              0
has_neighborhood_overview         0
has_reviews                       0
host_in_CO                        0
host_lives_in_neighborhood        0
host_id                           0
host_name                         0
host_response_time              377
host_response_rate              377
host_acceptance_rate            224
host_is_superhost                 0
host_neighbourhood              204
host_listings_count               0
host_total_listings_count         0
host_has_profile_pic              0
host_identity_verified            0
has_host_about                    0
years_hosting                     0
years_of_reviews                  0
license_listed                    0
response_time                     0
host_lives_in_neighborhood.1      0
name                              0
host_about                      524
description                       7
neighborhood_overview           271
amenities                         0
minimum_nights                    0
maximum_nights                    0
min_stay_group                    0
max_stay_group                    0
has_availability                  0
availability_30                   0
availability_60                   0
availability_90                   0
availability_365                  0
instant_bookable                  0
number_of_reviews                 0
number_of_reviews_ltm             0
number_of_reviews_l30d            0
review_scores_rating             75
review_scores_accuracy           79
review_scores_cleanliness        79
review_scores_checkin            79
review_scores_communication      79
review_scores_location           79
review_scores_value              79
reviews_per_month                75
bike_scores                       0
walk_scores                       0
transit_scores                   77
property_page_links               0
25*k                              0
dtype: int64

In [73]:
# added2.to_csv('../data/added2.csv', index=False)

# creating an api df

In [127]:

api=df[['id', 'latitude', 'longitude','bike_scores', 'walk_scores', 'transit_scores', 'property_page_links']]

In [42]:
api.head()

,id,latitude,longitude,bike_scores,walk_scores,transit_scores,property_page_links
0,177,39.69551,-104.92489,84,51,37.0,https://www.walkscore.com/score/loc/lat=39.695...
1,360,39.76758,-105.00316,93,90,49.0,https://www.walkscore.com/score/loc/lat=39.767...
2,2361919,39.77960,-105.03859,76,81,34.0,https://www.walkscore.com/score/loc/lat=39.779...
3,2386289,39.76777,-105.03529,75,86,39.0,https://www.walkscore.com/score/loc/lat=39.767...
4,4992412,39.76822,-105.00249,93,90,49.0,https://www.walkscore.com/score/loc/lat=39.768...

In [60]:
# api.to_csv('../data/all_api.csv', index=False)

(5050, 7)

In [185]:
api.isna().sum()

id                        0
latitude                  0
longitude                 0
bike_scores               0
walk_scores               0
transit_scores         4051
property_page_links       0
dtype: int64

In [ ]:
# df.to_csv('../data/allAPI.csv', index=False)

In [59]:
allAPI = pd.read_csv('../data/building_transit_api.csv')
allAPI.shape

(1879, 64)

In [86]:
cleaned = pd.read_csv('dec/cleaned450.csv')

In [87]:
cleaned.shape

(5030, 59)

In [88]:
cleaned.head(2)

,id,latitude,longitude,price,25*k,shared_status,accommodates,accomodation_group,bathrooms,bedrooms,beds_adjusted,neighborhood,city,has_neighborhood_overview,host_in_CO,host_lives_in_neighborhood,host_id,host_name,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,host_total_listings_count,host_has_profile_pic,host_identity_verified,has_host_about,years_hosting,years_of_reviews,license_listed,response_time,host_lives_in_neighborhood.1,name,host_about,description,neighborhood_overview,amenities,minimum_nights,maximum_nights,min_stay_group,max_stay_group,has_availability,availability_30,availability_60,availability_90,availability_365,instant_bookable,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
0,177,39.69551,-104.92489,79.0,3.0,entire home,2,0-2,1.0,1.0,1.0,Virginia Village,Denver,1,1,1,615,Joe,within an hour,1.0,1.00,1,Virginia Village,2.0,2.0,1.0,0.0,1,15.0,6.0,1,0.0,1,Tiny Home in the Heart of the City- ECO FRIENDLY,"I'm originally from Oklahoma, but have lived i...","160 sq ft + 80 sq ft loft for sleeping, Sleeps...","Quiet neighborhood next to park, creeks and bi...","[""Hot water"", ""Long term stays allowed"", ""Coff...",29,400,month,long_term,1,29,59,89,364,0,120,24,0,4.85,4.96,4.89,4.97,4.94,4.85,4.78,1.56
1,360,39.76758,-105.00316,133.0,5.0,entire home,3,3-4,1.0,2.0,2.0,Highland,Denver,1,1,1,666,Jennifer & Giovanni,within an hour,1.0,0.87,1,Highland,4.0,4.0,1.0,1.0,1,15.0,4.0,1,0.0,1,Sit in the Peaceful Garden of the Chickadee Co...,We are artists and tinkerers.\r\n \r\nWe enjoy...,Enjoy the famous Colorado weather and unplug i...,The cottage is located in the center of Lower ...,"[""Coffee maker"", ""Washer"", ""Bedroom comforts"",...",29,35,month,2_months,1,0,0,30,30,0,174,7,1,4.99,4.99,4.96,5.00,5.00,5.00,4.91,3.26

In [89]:
merged= cleaned.merge(api, on=['id','latitude', 'longitude'], how='left')

In [2]:
bdi = pd.read_csv('../data/building_transit_api.csv')

NameError: name 'pd' is not defined

In [223]:
apis= pd.read_csv('dec/all_api.csv')

In [224]:
filler = pd.read_csv('dec/filler.csv')

In [225]:
filler.shape

(5218, 75)

In [226]:
apis.shape

(5238, 7)

In [227]:
apis.isna().sum()

id                        0
latitude                  0
longitude                 0
bike_scores             188
walk_scores             188
transit_scores         4239
property_page_links     188
dtype: int64

In [195]:
merged2= cleaned2.merge(all_api, on=['id','latitude', 'longitude'], how='left')

In [210]:
filler.isna().sum()

id                               0
latitude                         0
longitude                        0
price                            0
25*k                             0
                              ...
review_scores_checkin          892
review_scores_communication    892
review_scores_location         892
review_scores_value            892
reviews_per_month              888
Length: 62, dtype: int64

In [228]:
#first go round with the api pull didn't get all the more expensive houses...  
missing=filler[filler['bike_scores'].isna()]

In [229]:
missing.shape

(188, 75)

In [245]:
missing = missing.drop(columns=['bike_scores', 'walk_scores','transit_scores','property_page_links'])

In [246]:
# Extract the latitude and longitude values
latitudes = missing['latitude']
longitudes = missing['longitude']

# Make API requests to get the walk scores, bike scores, and property page links
results = []
for lat, long in zip(latitudes, longitudes):
    result = walkscore_api.get_score(latitude=lat, longitude=long, return_transit_score=True)
    results.append(result)

# Extract the bike scores, walk scores, and property page links from the results
bike_scores = [result.bike_score for result in results]
walk_scores = [result.walk_score for result in results]
property_page_links = [result.property_page_link for result in results]
transit_scores = [result.transit_score for result in results]

# Add the bike scores, walk scores, and property page links to the corresponding rows of the dataframe
missing['bike_scores'] = bike_scores
missing['walk_scores'] = walk_scores
missing['transit_scores'] = transit_scores
missing['property_page_links'] = property_page_links

In [247]:
missing.isna().sum()

id                                               0
listing_url                                      0
name                                             0
description                                      2
neighborhood_overview                           40
host_id                                          0
host_url                                         0
host_name                                        0
host_since                                       0
host_location                                    0
host_about                                      65
host_response_time                              32
host_response_rate                              32
host_acceptance_rate                            21
host_is_superhost                                0
host_neighbourhood                              15
host_listings_count                              0
host_total_listings_count                        0
host_verifications                               0
host_has_profile_pic                             0
host_identity_verified                           0
latitude                                         0
longitude                                        0
property_type                                    0
accommodates                                     0
bathrooms                                        0
bedrooms                                         0
amenities                                        0
price                                            0
minimum_nights                                   0
maximum_nights                                   0
has_availability                                 0
availability_30                                  0
availability_60                                  0
availability_90                                  0
availability_365                                 0
number_of_reviews                                0
number_of_reviews_ltm                            0
number_of_reviews_l30d                           0
first_review                                    30
last_review                                     30
review_scores_rating                            30
review_scores_accuracy                          30
review_scores_cleanliness                       30
review_scores_checkin                           30
review_scores_communication                     30
review_scores_location                          30
review_scores_value                             30
instant_bookable                                 0
calculated_host_listings_count                   0
calculated_host_listings_count_entire_homes      0
calculated_host_listings_count_private_rooms     0
calculated_host_listings_count_shared_rooms      0
reviews_per_month                               30
has_neighborhood_overview                        0
has_host_about                                   0
has_reviews                                      0
years_hosting                                    0
years_of_reviews                                 0
license_listed                                   0
response_time                                    0
host_in_CO                                       0
host_lives_in_neighborhood                       0
city                                             0
neighborhood                                     0
min_stay_group                                   0
max_stay_group                                   0
beds_adjusted                                    0
shared_status                                    0
25*k                                             0
accomodation_group                               0
bike_scores                                      0
walk_scores                                      0
transit_scores                                   0
property_page_links                              0
dtype: int64

In [248]:
missing.to_csv('dec/missing_api.csv', index=False)

In [250]:
#easier to just drop the rows witth missing bike scores and then just add the rows back in
rest = filler.dropna(subset=['bike_scores'])

In [252]:
all= pd.concat([rest, missing], ignore_index=True)

In [253]:
all.shape

(5218, 75)

In [254]:
all.isna().sum()

id                                                 0
listing_url                                        0
name                                               0
description                                       21
neighborhood_overview                           1502
host_id                                            0
host_url                                           0
host_name                                          1
host_since                                         1
host_location                                      0
host_about                                      1979
host_response_time                               729
host_response_rate                               729
host_acceptance_rate                             425
host_is_superhost                                  0
host_neighbourhood                               299
host_listings_count                                1
host_total_listings_count                          1
host_verifications                                 0
host_has_profile_pic                               1
host_identity_verified                             1
latitude                                           0
longitude                                          0
property_type                                      0
accommodates                                       0
bathrooms                                          0
bedrooms                                           0
amenities                                          0
price                                              0
minimum_nights                                     0
maximum_nights                                     0
has_availability                                   0
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
first_review                                     888
last_review                                      888
review_scores_rating                             888
review_scores_accuracy                           892
review_scores_cleanliness                        892
review_scores_checkin                            892
review_scores_communication                      892
review_scores_location                           892
review_scores_value                              892
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                                888
bike_scores                                        0
walk_scores                                        0
transit_scores                                  4039
property_page_links                                0
has_neighborhood_overview                          0
has_host_about                                     0
has_reviews                                        0
years_hosting                                      0
years_of_reviews                                   0
license_listed                                     0
response_time                                      0
host_in_CO                                         0
host_lives_in_neighborhood                         0
city                                               0
neighborhood                                       0
min_stay_group                                     0
max_stay_group                                     0
beds_adjusted                                      0
shared_status                                      0
25*k                                               0
accomodation_group                                 0
dtype: int64

In [255]:
# all.to_csv('dec/allAPI.csv', index=False)

In [256]:
missing_api=missing[['id', 'latitude', 'longitude','bike_scores', 'walk_scores', 'transit_scores', 'property_page_links']]

In [257]:
all_api=pd.concat([api, missing_api], ignore_index=True)

In [258]:
api.shape

(5050, 7)

In [259]:
missing_api.shape

(188, 7)

In [260]:
missing_api.isna().sum()

id                     0
latitude               0
longitude              0
bike_scores            0
walk_scores            0
transit_scores         0
property_page_links    0
dtype: int64

In [261]:
all_api.shape

(5238, 7)

In [262]:
# all_api.to_csv('dec/all_api.csv', index=False)

In [263]:
all_api.isna().sum()

id                        0
latitude                  0
longitude                 0
bike_scores               0
walk_scores               0
transit_scores         4051
property_page_links       0
dtype: int64

# where the fuck am I?

In [144]:
bti = pd.read_csv('../data/building_transit_api.csv')

In [145]:
bti.shape

(1879, 64)

In [146]:
bti.head()

,id,latitude,longitude,price,shared_status,accommodates,accomodation_group,bathrooms,bedrooms,beds_adjusted,neighborhood,city,has_neighborhood_overview,has_reviews,host_in_CO,host_lives_in_neighborhood,host_id,host_name,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,host_total_listings_count,host_has_profile_pic,host_identity_verified,has_host_about,years_hosting,years_of_reviews,license_listed,response_time,host_lives_in_neighborhood.1,name,host_about,description,neighborhood_overview,amenities,minimum_nights,maximum_nights,min_stay_group,max_stay_group,has_availability,availability_30,availability_60,availability_90,availability_365,instant_bookable,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month,bike_scores,walk_scores,transit_scores,property_page_links,25*k
0,177,39.69551,-104.92489,79.0,entire home,2,0-2,1.0,1.0,1.0,Virginia Village,Denver,1,1,1,1,615,Joe,within an hour,1.0,1.00,1.0,Virginia Village,2.0,2.0,1.0,0.0,1,15.0,6.0,1,0.0,1,Tiny Home in the Heart of the City- ECO FRIENDLY,"I'm originally from Oklahoma, but have lived i...","160 sq ft + 80 sq ft loft for sleeping, Sleeps...","Quiet neighborhood next to park, creeks and bi...","[""Hot water"", ""Long term stays allowed"", ""Coff...",29,400,month,long_term,1,29,59,89,364,0,120,24,0,4.85,4.96,4.89,4.97,4.94,4.85,4.78,1.56,84.0,51.0,37.0,https://www.walkscore.com/score/loc/lat=39.695...,4.0
1,360,39.76758,-105.00316,133.0,entire home,3,3-4,1.0,2.0,2.0,Highland,Denver,1,1,1,1,666,Jennifer & Giovanni,within an hour,1.0,0.87,1.0,Highland,4.0,4.0,1.0,1.0,1,15.0,4.0,1,0.0,1,Sit in the Peaceful Garden of the Chickadee Co...,We are artists and tinkerers.\r\n \r\nWe enjoy...,Enjoy the famous Colorado weather and unplug i...,The cottage is located in the center of Lower ...,"[""Coffee maker"", ""Washer"", ""Bedroom comforts"",...",29,35,month,2_months,1,0,0,30,30,0,174,7,1,4.99,4.99,4.96,5.00,5.00,5.00,4.91,3.26,93.0,90.0,49.0,https://www.walkscore.com/score/loc/lat=39.767...,6.0
2,2361919,39.77960,-105.03859,76.0,entire home,2,0-2,1.0,1.0,1.0,Berkeley,Denver,1,1,1,1,5811115,Annette,within a few hours,1.0,0.81,1.0,Berkeley,5.0,6.0,1.0,0.0,1,10.0,8.0,0,1.0,1,The Cloisters at Berkeley,"I love people of all ages and types, dogs, lon...",A private studio apartment in an unbeatable ne...,"Boutiques, bars, restaurants galore! Highlands...","[""Hot water"", ""Long term stays allowed"", ""Coff...",30,1125,month,long_term,1,24,54,84,359,0,43,3,0,4.67,4.74,4.56,4.67,4.60,4.93,4.60,0.40,76.0,81.0,34.0,https://www.walkscore.com/score/loc/lat=39.779...,4.0
3,2386289,39.76777,-105.03529,150.0,entire home,4,3-4,1.0,1.0,1.0,West Highland,Denver,1,1,1,1,184771,Melanie,NaN,NaN,1.00,0.0,West Highland,1.0,2.0,1.0,1.0,1,13.0,8.0,1,4.0,1,Sunny Sky Loft in Highlands,"Things I love: dogs, urban gardening, yoga, ho...",Why stay in a stuffy old hotel room when you c...,The neighborhood where the house is located is...,"[""Hot water"", ""Long term stays allowed"", ""Coff...",7,30,week,month,1,0,0,0,0,0,95,1,0,4.91,4.87,4.89,4.96,4.97,4.93,4.83,0.94,75.0,86.0,39.0,https://www.walkscore.com/score/loc/lat=39.767...,7.0
4,4992412,39.76822,-105.00249,73.0,private room,2,0-2,2.0,1.0,1.0,Highland,Denver,1,0,1,1,5181201,Danno & Rachel,NaN,NaN,0.00,0.0,Highland,3.0,4.0,1.0,1.0,1,10.0,0.0,0,4.0,1,"Cozy Cottage in Lo Highlands, 2nd b","Danno, 40- yo professional from Aspen, Colorad...",You are renting the second bedroom of a 2br 2b...,My house is located on the edge of all the act...,"[""Long term stays allowed"", ""Free parking on p...",30,1125,month,long_term,1,0,0,0,183,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,93.0,90.0,49.0,https://www.walkscore.com/score/loc/lat=39.768...,3.0

In [149]:
added2 = pd.read_csv('../data/added2.csv')

In [150]:
added2.shape

(2778, 64)

In [151]:
added2.isna().sum()

id                                0
latitude                          0
longitude                         0
price                             0
shared_status                     0
accommodates                      0
accomodation_group                0
bathrooms                         0
bedrooms                          0
beds_adjusted                     0
neighborhood                      0
city                              0
has_neighborhood_overview         0
has_reviews                       0
host_in_CO                        0
host_lives_in_neighborhood        0
host_id                           0
host_name                         0
host_response_time              525
host_response_rate              525
host_acceptance_rate            303
host_is_superhost                 0
host_neighbourhood              244
host_listings_count               0
host_total_listings_count         0
host_has_profile_pic              0
host_identity_verified            0
has_host_about                    0
years_hosting                     0
years_of_reviews                  0
license_listed                    0
response_time                     0
host_lives_in_neighborhood.1      0
name                              0
host_about                      938
description                      19
neighborhood_overview           555
amenities                         0
minimum_nights                    0
maximum_nights                    0
min_stay_group                    0
max_stay_group                    0
has_availability                  0
availability_30                   0
availability_60                   0
availability_90                   0
availability_365                  0
instant_bookable                  0
number_of_reviews                 0
number_of_reviews_ltm             0
number_of_reviews_l30d            0
review_scores_rating            133
review_scores_accuracy          137
review_scores_cleanliness       137
review_scores_checkin           137
review_scores_communication     137
review_scores_location          137
review_scores_value             137
reviews_per_month               133
bike_scores                       0
walk_scores                       0
transit_scores                   78
property_page_links               0
25*k                              0
dtype: int64

In [152]:
cleanedall = pd.read_csv('../data/cleanedall.csv')

In [153]:
mergedAPI= pd.read_csv('../data/mergedAPI.csv')

In [154]:
mergedAPI.isna().sum()

id                                 0
latitude                           0
longitude                          0
price                              0
shared_status                      0
accommodates                       0
accomodation_group                 0
bathrooms                          0
bedrooms                           0
beds_adjusted                      0
neighborhood                       0
city                               0
has_neighborhood_overview          0
has_reviews                        0
host_in_CO                         0
host_lives_in_neighborhood         0
host_id                            0
host_name                          0
host_response_time               734
host_response_rate               734
host_acceptance_rate             429
host_is_superhost                  0
host_neighbourhood               304
host_listings_count                0
host_total_listings_count          0
host_has_profile_pic               0
host_identity_verified             0
has_host_about                     0
years_hosting                      0
years_of_reviews                   0
license_listed                     0
response_time                      0
host_lives_in_neighborhood.1       0
name                               0
host_about                      1994
description                       23
neighborhood_overview           1519
amenities                          0
minimum_nights                     0
maximum_nights                     0
min_stay_group                     0
max_stay_group                     0
has_availability                   0
availability_30                    0
availability_60                    0
availability_90                    0
availability_365                   0
instant_bookable                   0
number_of_reviews                  0
number_of_reviews_ltm              0
number_of_reviews_l30d             0
review_scores_rating             898
review_scores_accuracy           902
review_scores_cleanliness        902
review_scores_checkin            902
review_scores_communication      902
review_scores_location           902
review_scores_value              902
reviews_per_month                898
bike_scores                       12
walk_scores                       12
transit_scores                  4062
property_page_links               12
dtype: int64

In [155]:
cleaned_missing=mergedAPI[mergedAPI['transit_scores'].isna()]

In [156]:
cleaned_messing

NameError: name 'cleaned_messing' is not defined

In [157]:
cleaned_missing=cleaned_missing.merge

In [158]:
allapi = pd.read_csv('../data/all_api.csv')

In [159]:
allapi.shape

(5238, 7)

In [160]:
allapi.head()

,id,latitude,longitude,bike_scores,walk_scores,transit_scores,property_page_links
0,177,39.69551,-104.92489,84,51,37.0,https://www.walkscore.com/score/loc/lat=39.695...
1,360,39.76758,-105.00316,93,90,49.0,https://www.walkscore.com/score/loc/lat=39.767...
2,2361919,39.77960,-105.03859,76,81,34.0,https://www.walkscore.com/score/loc/lat=39.779...
3,2386289,39.76777,-105.03529,75,86,39.0,https://www.walkscore.com/score/loc/lat=39.767...
4,4992412,39.76822,-105.00249,93,90,49.0,https://www.walkscore.com/score/loc/lat=39.768...

In [161]:
allapi.isna().sum()

id                        0
latitude                  0
longitude                 0
bike_scores               0
walk_scores               0
transit_scores         4051
property_page_links       0
dtype: int64

In [162]:
added_transit= added2[['id', 'transit_scores']]
added_transit.head()

        id  transit_scores
0      177            37.0
1      360            49.0
2  2361919            34.0
3  2386289            39.0
4  4992412            49.0

In [163]:
added_transit.shape

(2778, 2)

In [164]:
added_transit.isna().sum()

id                 0
transit_scores    78
dtype: int64

In [175]:
merged_transit.head()

        id  transit_scores
0      177            37.0
1      360            49.0
2  2361919            34.0
3  2386289            39.0
4  4992412            49.0

In [165]:
merged_transit=mergedAPI[['id', 'transit_scores']]

In [166]:
merged_transit.shape

(5249, 2)

In [167]:
merged_transit.isna().sum()

id                   0
transit_scores    4062
dtype: int64

In [168]:
merged = pd.merge(added_transit, merged_transit, on='id')

In [169]:
merged.shape

(2778, 3)

In [170]:
merged.head()

        id  transit_scores_x  transit_scores_y
0      177              37.0              37.0
1      360              49.0              49.0
2  2361919              34.0              34.0
3  2386289              39.0              39.0
4  4992412              49.0              49.0

In [171]:
cleanedall.head()

,id,latitude,longitude,price,shared_status,accommodates,accomodation_group,bathrooms,bedrooms,beds_adjusted,neighborhood,city,has_neighborhood_overview,has_reviews,host_in_CO,host_lives_in_neighborhood,host_id,host_name,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,host_total_listings_count,host_has_profile_pic,host_identity_verified,has_host_about,years_hosting,years_of_reviews,license_listed,response_time,host_lives_in_neighborhood.1,name,host_about,description,neighborhood_overview,amenities,minimum_nights,maximum_nights,min_stay_group,max_stay_group,has_availability,availability_30,availability_60,availability_90,availability_365,instant_bookable,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
0,177,39.69551,-104.92489,$79.00,entire home,2,0-2,1.0,1.0,1.0,Virginia Village,Denver,1,1,1,1,615,Joe,within an hour,1.0,1.00,1.0,Virginia Village,2.0,2.0,1.0,0.0,1,15.0,6.0,1,0.0,1,Tiny Home in the Heart of the City- ECO FRIENDLY,"I'm originally from Oklahoma, but have lived i...","160 sq ft + 80 sq ft loft for sleeping, Sleeps...","Quiet neighborhood next to park, creeks and bi...","[""Hot water"", ""Long term stays allowed"", ""Coff...",29,400,month,long_term,1,29,59,89,364,0,120,24,0,4.85,4.96,4.89,4.97,4.94,4.85,4.78,1.56
1,360,39.76758,-105.00316,$133.00,entire home,3,3-4,1.0,2.0,2.0,Highland,Denver,1,1,1,1,666,Jennifer & Giovanni,within an hour,1.0,0.87,1.0,Highland,4.0,4.0,1.0,1.0,1,15.0,4.0,1,0.0,1,Sit in the Peaceful Garden of the Chickadee Co...,We are artists and tinkerers.\r\n \r\nWe enjoy...,Enjoy the famous Colorado weather and unplug i...,The cottage is located in the center of Lower ...,"[""Coffee maker"", ""Washer"", ""Bedroom comforts"",...",29,35,month,2_months,1,0,0,30,30,0,174,7,1,4.99,4.99,4.96,5.00,5.00,5.00,4.91,3.26
2,2361919,39.77960,-105.03859,$76.00,entire home,2,0-2,1.0,1.0,1.0,Berkeley,Denver,1,1,1,1,5811115,Annette,within a few hours,1.0,0.81,1.0,Berkeley,5.0,6.0,1.0,0.0,1,10.0,8.0,0,1.0,1,The Cloisters at Berkeley,"I love people of all ages and types, dogs, lon...",A private studio apartment in an unbeatable ne...,"Boutiques, bars, restaurants galore! Highlands...","[""Hot water"", ""Long term stays allowed"", ""Coff...",30,1125,month,long_term,1,24,54,84,359,0,43,3,0,4.67,4.74,4.56,4.67,4.60,4.93,4.60,0.40
3,2386289,39.76777,-105.03529,$150.00,entire home,4,3-4,1.0,1.0,1.0,West Highland,Denver,1,1,1,1,184771,Melanie,NaN,NaN,1.00,0.0,West Highland,1.0,2.0,1.0,1.0,1,13.0,8.0,1,4.0,1,Sunny Sky Loft in Highlands,"Things I love: dogs, urban gardening, yoga, ho...",Why stay in a stuffy old hotel room when you c...,The neighborhood where the house is located is...,"[""Hot water"", ""Long term stays allowed"", ""Coff...",7,30,week,month,1,0,0,0,0,0,95,1,0,4.91,4.87,4.89,4.96,4.97,4.93,4.83,0.94
4,4992412,39.76822,-105.00249,$73.00,private room,2,0-2,2.0,1.0,1.0,Highland,Denver,1,0,1,1,5181201,Danno & Rachel,NaN,NaN,0.00,0.0,Highland,3.0,4.0,1.0,1.0,1,10.0,0.0,0,4.0,1,"Cozy Cottage in Lo Highlands, 2nd b","Danno, 40- yo professional from Aspen, Colorad...",You are renting the second bedroom of a 2br 2b...,My house is located on the edge of all the act...,"[""Long term stays allowed"", ""Free parking on p...",30,1125,month,long_term,1,0,0,0,183,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [172]:
cleanedall.isna().sum()

id                                 0
latitude                           0
longitude                          0
price                              0
shared_status                      0
accommodates                       0
accomodation_group                 0
bathrooms                          0
bedrooms                           0
beds_adjusted                      0
neighborhood                       0
city                               0
has_neighborhood_overview          0
has_reviews                        0
host_in_CO                         0
host_lives_in_neighborhood         0
host_id                            0
host_name                          0
host_response_time               734
host_response_rate               734
host_acceptance_rate             429
host_is_superhost                  0
host_neighbourhood               304
host_listings_count                0
host_total_listings_count          0
host_has_profile_pic               0
host_identity_verified             0
has_host_about                     0
years_hosting                      0
years_of_reviews                   0
license_listed                     0
response_time                      0
host_lives_in_neighborhood.1       0
name                               0
host_about                      1994
description                       23
neighborhood_overview           1519
amenities                          0
minimum_nights                     0
maximum_nights                     0
min_stay_group                     0
max_stay_group                     0
has_availability                   0
availability_30                    0
availability_60                    0
availability_90                    0
availability_365                   0
instant_bookable                   0
number_of_reviews                  0
number_of_reviews_ltm              0
number_of_reviews_l30d             0
review_scores_rating             898
review_scores_accuracy           902
review_scores_cleanliness        902
review_scores_checkin            902
review_scores_communication      902
review_scores_location           902
review_scores_value              902
reviews_per_month                898
dtype: int64

In [176]:
cleanedall.shape

(5249, 59)

In [177]:
cleanedall_notransit=cleanedall.drop('transit_scores', axis=1)

KeyError: "['transit_scores'] not found in axis"

In [178]:
cleanedall_notransit.head()

,id,latitude,longitude,bike_scores,walk_scores,property_page_links
0,177,39.69551,-104.92489,84,51,https://www.walkscore.com/score/loc/lat=39.695...
1,360,39.76758,-105.00316,93,90,https://www.walkscore.com/score/loc/lat=39.767...
2,2361919,39.77960,-105.03859,76,81,https://www.walkscore.com/score/loc/lat=39.779...
3,2386289,39.76777,-105.03529,75,86,https://www.walkscore.com/score/loc/lat=39.767...
4,4992412,39.76822,-105.00249,93,90,https://www.walkscore.com/score/loc/lat=39.768...

In [179]:
merged = pd.merge(cleanedall_notransit, added_transit, on='id', how='left')

In [180]:
merged.head()

,id,latitude,longitude,bike_scores,walk_scores,property_page_links,transit_scores
0,177,39.69551,-104.92489,84,51,https://www.walkscore.com/score/loc/lat=39.695...,37.0
1,360,39.76758,-105.00316,93,90,https://www.walkscore.com/score/loc/lat=39.767...,49.0
2,2361919,39.77960,-105.03859,76,81,https://www.walkscore.com/score/loc/lat=39.779...,34.0
3,2386289,39.76777,-105.03529,75,86,https://www.walkscore.com/score/loc/lat=39.767...,39.0
4,4992412,39.76822,-105.00249,93,90,https://www.walkscore.com/score/loc/lat=39.768...,49.0

In [181]:
merged.isna().sum()

id                        0
latitude                  0
longitude                 0
bike_scores               0
walk_scores               0
property_page_links       0
transit_scores         2538
dtype: int64

In [182]:
merged_missing=merged[merged['transit_scores'].isna()]

In [183]:
merged_missing.shape

(2538, 7)

In [184]:
merged_there=merged[merged['transit_scores'].notna()]

In [185]:
merged_there.shape

(2700, 7)

In [186]:
merged_there.head()

,id,latitude,longitude,bike_scores,walk_scores,property_page_links,transit_scores
0,177,39.69551,-104.92489,84,51,https://www.walkscore.com/score/loc/lat=39.695...,37.0
1,360,39.76758,-105.00316,93,90,https://www.walkscore.com/score/loc/lat=39.767...,49.0
2,2361919,39.77960,-105.03859,76,81,https://www.walkscore.com/score/loc/lat=39.779...,34.0
3,2386289,39.76777,-105.03529,75,86,https://www.walkscore.com/score/loc/lat=39.767...,39.0
4,4992412,39.76822,-105.00249,93,90,https://www.walkscore.com/score/loc/lat=39.768...,49.0

In [187]:
merged_missing1 = merged_missing.iloc[:1200] 
merged_missing2 = merged_missing.iloc[1201:]

In [188]:
merged_missing1=merged_missing1.drop('transit_scores', axis=1)

In [189]:
merged_missing1.head()

,id,latitude,longitude,bike_scores,walk_scores,property_page_links
126,7052545,39.76662,-105.05283,65,80,https://www.walkscore.com/score/loc/lat=39.766...
286,9135545,39.76631,-105.05273,65,80,https://www.walkscore.com/score/loc/lat=39.766...
316,9445553,39.76582,-105.05254,65,80,https://www.walkscore.com/score/loc/lat=39.765...
318,9446217,39.76581,-105.05252,65,80,https://www.walkscore.com/score/loc/lat=39.765...
409,13579869,39.76786,-105.05258,65,85,https://www.walkscore.com/score/loc/lat=39.767...

In [190]:
merged_missing2=merged_missing2.drop('transit_scores', axis=1)

In [191]:
api_key = 'bfbd763410626e5d278b9430e7d89c3e'

walkscore_api = WalkScoreAPI(api_key = api_key)

# Extract the latitude and longitude values
latitudes = merged_missing2['latitude']
longitudes = merged_missing2['longitude']

# Make API requests to get the walk scores, bike scores, and property page links
results = []
for lat, long in zip(latitudes, longitudes):
    result = walkscore_api.get_score(latitude=lat, longitude=long, return_transit_score=True)
    results.append(result)

# Extract the bike scores, walk scores, and property page links from the results
bike_scores = [result.bike_score for result in results]
walk_scores = [result.walk_score for result in results]
property_page_links = [result.property_page_link for result in results]
transit_scores = [result.transit_score for result in results]

# Add the bike scores, walk scores, and property page links to the corresponding rows of the dataframe
# missing['bike_scores'] = bike_scores
# missing['walk_scores'] = walk_scores
merged_missing2['transit_scores'] = transit_scores
# missing['property_page_links'] = property_page_links

In [192]:
merged_missing2.shape

(1337, 7)

In [193]:
merged_missing2.isna().sum()

id                       0
latitude                 0
longitude                0
bike_scores              0
walk_scores              0
property_page_links      0
transit_scores         337
dtype: int64

In [194]:
merged_missing2_has_transit= merged_missing2[merged_missing2['transit_scores'].notna()]

In [196]:
merged_missing2_has_transit.head()

,id,latitude,longitude,bike_scores,walk_scores,property_page_links,transit_scores
3713,610728030179356704,39.745200,-104.992810,93,98,https://www.walkscore.com/score/loc/lat=39.745...,87.0
3714,618721957268988435,39.790610,-105.038650,47,48,https://www.walkscore.com/score/loc/lat=39.790...,32.0
3715,618739409351413763,39.758802,-104.915517,86,48,https://www.walkscore.com/score/loc/lat=39.758...,46.0
3716,618752055548548753,39.755085,-105.001137,91,92,https://www.walkscore.com/score/loc/lat=39.755...,85.0
3717,618787870092598779,39.714690,-104.984210,96,93,https://www.walkscore.com/score/loc/lat=39.714...,60.0

In [200]:
merged_missing2_has_transit.isna().sum()

id                     0
latitude               0
longitude              0
bike_scores            0
walk_scores            0
property_page_links    0
transit_scores         0
dtype: int64

In [198]:
merged_missing2_has_transit.shape

(1000, 7)

In [197]:
merged_there.head()

,id,latitude,longitude,bike_scores,walk_scores,property_page_links,transit_scores
0,177,39.69551,-104.92489,84,51,https://www.walkscore.com/score/loc/lat=39.695...,37.0
1,360,39.76758,-105.00316,93,90,https://www.walkscore.com/score/loc/lat=39.767...,49.0
2,2361919,39.77960,-105.03859,76,81,https://www.walkscore.com/score/loc/lat=39.779...,34.0
3,2386289,39.76777,-105.03529,75,86,https://www.walkscore.com/score/loc/lat=39.767...,39.0
4,4992412,39.76822,-105.00249,93,90,https://www.walkscore.com/score/loc/lat=39.768...,49.0

In [199]:
merged_there.shape

(2700, 7)

In [201]:
merging_there_plus_missing2=pd.concat([merged_there, merged_missing2_has_transit])

In [202]:
merging_there_plus_missing2.shape

(3700, 7)

In [203]:
merging_there_plus_missing2.isna().sum()

id                     0
latitude               0
longitude              0
bike_scores            0
walk_scores            0
property_page_links    0
transit_scores         0
dtype: int64

In [214]:
# merging_there_plus_missing2.to_csv('../data/merged3.csv')

In [204]:
merged_missing2_no_transit= merged_missing2[merged_missing2['transit_scores'].isna()]

In [205]:
merged_missing2_no_transit.shape

(337, 7)

In [206]:
merged_missing2_no_transit.isna().sum()

id                       0
latitude                 0
longitude                0
bike_scores              0
walk_scores              0
property_page_links      0
transit_scores         337
dtype: int64

In [207]:
merged_missing2_no_transit_6=merged_missing2_no_transit.drop('transit_scores', axis=1)

In [209]:
merged_missing2_no_transit_6.shape

(337, 6)

In [211]:
still_missing=pd.concat([merged_missing1, merged_missing2_no_transit_6])
still_missing.shape

(1537, 6)

In [212]:
still_missing.isna().sum()

id                     0
latitude               0
longitude              0
bike_scores            0
walk_scores            0
property_page_links    0
dtype: int64

In [215]:
still_missing1 = still_missing.iloc[:800] 
still_missing2 = still_missing.iloc[801:]

In [217]:
still_missing1['walk_scores'].mean()

77.385

In [218]:
still_missing1.to_csv('../data/still_missing1.csv')
still_missing2.to_csv('../data/still_missing2.csv')

In [14]:
still_missing2 = pd.read_csv('../data/still_missing2.csv')

still_missing2.head(2)

,Unnamed: 0,id,latitude,longitude,bike_scores,walk_scores,property_page_links
0,3313,535408542916708813,39.74857,-105.02395,75,83,https://www.walkscore.com/score/loc/lat=39.748...
1,3314,539127064753450225,39.71583,-105.03657,78,74,https://www.walkscore.com/score/loc/lat=39.715...

In [15]:
still_missing2 = still_missing2.drop('Unnamed: 0', axis=1)

In [16]:
still_missing2.head(2)

,id,latitude,longitude,bike_scores,walk_scores,property_page_links
0,535408542916708813,39.74857,-105.02395,75,83,https://www.walkscore.com/score/loc/lat=39.748...
1,539127064753450225,39.71583,-105.03657,78,74,https://www.walkscore.com/score/loc/lat=39.715...

In [17]:
df2 = pd.read_csv('../data/merged3.csv')

df2.head(2)

,Unnamed: 0,id,latitude,longitude,bike_scores,walk_scores,property_page_links,transit_scores
0,0,177,39.69551,-104.92489,84,51,https://www.walkscore.com/score/loc/lat=39.695...,37.0
1,1,360,39.76758,-105.00316,93,90,https://www.walkscore.com/score/loc/lat=39.767...,49.0

In [18]:
merged3 = df2.drop('Unnamed: 0', axis=1)

In [19]:
merged3.shape

(3700, 7)

In [20]:
api_key = 'bfbd763410626e5d278b9430e7d89c3e'

walkscore_api = WalkScoreAPI(api_key = api_key)

# Extract the latitude and longitude values
latitudes = still_missing2['latitude']
longitudes = still_missing2['longitude']

# Make API requests to get the walk scores, bike scores, and property page links
results = []
for lat, long in zip(latitudes, longitudes):
    result = walkscore_api.get_score(latitude=lat, longitude=long, return_transit_score=True)
    results.append(result)

# Extract the bike scores, walk scores, and property page links from the results
bike_scores = [result.bike_score for result in results]
walk_scores = [result.walk_score for result in results]
property_page_links = [result.property_page_link for result in results]
transit_scores = [result.transit_score for result in results]

# Add the bike scores, walk scores, and property page links to the corresponding rows of the dataframe
# missing['bike_scores'] = bike_scores
# missing['walk_scores'] = walk_scores
still_missing2['transit_scores'] = transit_scores
# missing['property_page_links'] = property_page_links

In [21]:
still_missing2.shape

(736, 7)

In [22]:
still_missing2.isna().sum()

id                     0
latitude               0
longitude              0
bike_scores            0
walk_scores            0
property_page_links    0
transit_scores         7
dtype: int64

In [23]:
still_missing2_transit= still_missing2[still_missing2['transit_scores'].notna()]

In [24]:
still_missing2_transit.shape

(729, 7)

In [25]:
still_missing2_transit.head(2)

,id,latitude,longitude,bike_scores,walk_scores,property_page_links,transit_scores
0,535408542916708813,39.74857,-105.02395,75,83,https://www.walkscore.com/score/loc/lat=39.748...,56.0
1,539127064753450225,39.71583,-105.03657,78,74,https://www.walkscore.com/score/loc/lat=39.715...,40.0

In [27]:
one_to_go=pd.concat([merged3, still_missing2_transit])

In [34]:
one_to_go.head()

,id,latitude,longitude,bike_scores,walk_scores,property_page_links,transit_scores
0,177,39.69551,-104.92489,84,51,https://www.walkscore.com/score/loc/lat=39.695...,37.0
1,360,39.76758,-105.00316,93,90,https://www.walkscore.com/score/loc/lat=39.767...,49.0
2,2361919,39.77960,-105.03859,76,81,https://www.walkscore.com/score/loc/lat=39.779...,34.0
3,2386289,39.76777,-105.03529,75,86,https://www.walkscore.com/score/loc/lat=39.767...,39.0
4,4992412,39.76822,-105.00249,93,90,https://www.walkscore.com/score/loc/lat=39.768...,49.0

In [51]:
one_to_go.shape

(4429, 7)

In [36]:
one_to_go.isna().sum()

id                     0
latitude               0
longitude              0
bike_scores            0
walk_scores            0
property_page_links    0
transit_scores         0
dtype: int64

In [37]:
one_to_go.to_csv('../data/one_to_go.csv')

In [38]:
still_missing2_notransit= still_missing2[still_missing2['transit_scores'].isna()]

In [40]:
still_missing2_notransit.shape

(7, 7)

In [44]:
still_missing2_notransit=still_missing2_notransit.drop('transit_scores', axis=1)

In [45]:
still_missing1 = pd.read_csv('../data/still_missing1.csv')

still_missing1.head(2)

,Unnamed: 0,id,latitude,longitude,bike_scores,walk_scores,property_page_links
0,126,7052545,39.76662,-105.05283,65,80,https://www.walkscore.com/score/loc/lat=39.766...
1,286,9135545,39.76631,-105.05273,65,80,https://www.walkscore.com/score/loc/lat=39.766...

In [52]:
still_missing1 = still_missing1.drop('Unnamed: 0', axis=1)
still_missing1.head()

,id,latitude,longitude,bike_scores,walk_scores,property_page_links
0,7052545,39.76662,-105.05283,65,80,https://www.walkscore.com/score/loc/lat=39.766...
1,9135545,39.76631,-105.05273,65,80,https://www.walkscore.com/score/loc/lat=39.766...
2,9445553,39.76582,-105.05254,65,80,https://www.walkscore.com/score/loc/lat=39.765...
3,9446217,39.76581,-105.05252,65,80,https://www.walkscore.com/score/loc/lat=39.765...
4,13579869,39.76786,-105.05258,65,85,https://www.walkscore.com/score/loc/lat=39.767...

In [53]:
still_missing1.shape

(800, 6)

In [48]:
last_missing=pd.concat([still_missing1, still_missing2_notransit])
last_missing.shape

(807, 7)

In [57]:
last_missing=last_missing.drop('Unnamed: 0', axis=1)
last_missing.head()

,id,latitude,longitude,bike_scores,walk_scores,property_page_links
0,7052545,39.76662,-105.05283,65,80,https://www.walkscore.com/score/loc/lat=39.766...
1,9135545,39.76631,-105.05273,65,80,https://www.walkscore.com/score/loc/lat=39.766...
2,9445553,39.76582,-105.05254,65,80,https://www.walkscore.com/score/loc/lat=39.765...
3,9446217,39.76581,-105.05252,65,80,https://www.walkscore.com/score/loc/lat=39.765...
4,13579869,39.76786,-105.05258,65,85,https://www.walkscore.com/score/loc/lat=39.767...

In [58]:
last_missing.shape

(807, 6)

In [59]:
# last_missing.to_csv('../data/last_missing.csv')

In [ ]:
# code from above

In [196]:
merged_missing2_has_transit.head()

,id,latitude,longitude,bike_scores,walk_scores,property_page_links,transit_scores
3713,610728030179356704,39.745200,-104.992810,93,98,https://www.walkscore.com/score/loc/lat=39.745...,87.0
3714,618721957268988435,39.790610,-105.038650,47,48,https://www.walkscore.com/score/loc/lat=39.790...,32.0
3715,618739409351413763,39.758802,-104.915517,86,48,https://www.walkscore.com/score/loc/lat=39.758...,46.0
3716,618752055548548753,39.755085,-105.001137,91,92,https://www.walkscore.com/score/loc/lat=39.755...,85.0
3717,618787870092598779,39.714690,-104.984210,96,93,https://www.walkscore.com/score/loc/lat=39.714...,60.0

In [33]:
merging_there_plus_missing2=pd.concat([merged_there, merged_missing2_has_transit])

NameError: name 'merged_there' is not defined

In [202]:
merging_there_plus_missing2.shape

(3700, 7)

In [32]:
merging_there_plus_missing2.isna().sum()

NameError: name 'merging_there_plus_missing2' is not defined

In [31]:
merging_there_plus_missing2.to_csv('../data/one_to_go.csv')

NameError: name 'merging_there_plus_missing2' is not defined

In [204]:
merged_missing2_no_transit= merged_missing2[merged_missing2['transit_scores'].isna()]

In [60]:
merged_missing2_no_transit.shape

NameError: name 'merged_missing2_no_transit' is not defined

In [206]:
merged_missing2_no_transit.isna().sum()

id                       0
latitude                 0
longitude                0
bike_scores              0
walk_scores              0
property_page_links      0
transit_scores         337
dtype: int64

In [207]:
merged_missing2_no_transit_6=merged_missing2_no_transit.drop('transit_scores', axis=1)

In [209]:
merged_missing2_no_transit_6.shape

(337, 6)

In [211]:
still_missing=pd.concat([merged_missing1, merged_missing2_no_transit_6])
still_missing.shape

(1537, 6)

In [ ]:
# last day?? Maybe?

In [4]:
last_missing= pd.read_csv('../data/last_missing.csv')

In [5]:
last_missing.head()

,Unnamed: 0,id,latitude,longitude,bike_scores,walk_scores,property_page_links
0,0,7052545,39.76662,-105.05283,65,80,https://www.walkscore.com/score/loc/lat=39.766...
1,1,9135545,39.76631,-105.05273,65,80,https://www.walkscore.com/score/loc/lat=39.766...
2,2,9445553,39.76582,-105.05254,65,80,https://www.walkscore.com/score/loc/lat=39.765...
3,3,9446217,39.76581,-105.05252,65,80,https://www.walkscore.com/score/loc/lat=39.765...
4,4,13579869,39.76786,-105.05258,65,85,https://www.walkscore.com/score/loc/lat=39.767...

In [6]:
last_missing=last_missing.drop('Unnamed: 0', axis=1)

In [7]:
one_to_go=pd.read_csv('../data/one_to_go.csv')

In [8]:
one_to_go.head()

,Unnamed: 0,id,latitude,longitude,bike_scores,walk_scores,property_page_links,transit_scores
0,0,177,39.69551,-104.92489,84,51,https://www.walkscore.com/score/loc/lat=39.695...,37.0
1,1,360,39.76758,-105.00316,93,90,https://www.walkscore.com/score/loc/lat=39.767...,49.0
2,2,2361919,39.77960,-105.03859,76,81,https://www.walkscore.com/score/loc/lat=39.779...,34.0
3,3,2386289,39.76777,-105.03529,75,86,https://www.walkscore.com/score/loc/lat=39.767...,39.0
4,4,4992412,39.76822,-105.00249,93,90,https://www.walkscore.com/score/loc/lat=39.768...,49.0

In [9]:
one_to_go=one_to_go.drop('Unnamed: 0', axis=1)

In [10]:
one_to_go.isna().sum()

id                     0
latitude               0
longitude              0
bike_scores            0
walk_scores            0
property_page_links    0
transit_scores         0
dtype: int64

In [11]:
last_missing.describe()

                 id    latitude   longitude  bike_scores  walk_scores
count  8.070000e+02  807.000000  807.000000   807.000000   807.000000
mean   6.450535e+15   39.740313 -104.982067    81.118959    77.172243
std    6.513488e+16    0.032501    0.058913    15.546240    20.071308
min    7.052545e+06   39.626000 -105.068560    15.000000     1.000000
25%    5.093634e+07   39.722043 -105.020936    72.000000    68.000000
50%    5.208969e+07   39.747750 -104.990320    85.000000    83.000000
75%    5.314691e+07   39.761645 -104.963885    94.000000    92.000000
max    7.807750e+17   39.809450 -104.736140    99.000000    98.000000

In [12]:
last_missing.shape

(807, 6)

In [13]:
api_key = 'bfbd763410626e5d278b9430e7d89c3e'

walkscore_api = WalkScoreAPI(api_key = api_key)

# Extract the latitude and longitude values
latitudes = last_missing['latitude']
longitudes = last_missing['longitude']

# Make API requests to get the walk scores, bike scores, and property page links
results = []
for lat, long in zip(latitudes, longitudes):
    result = walkscore_api.get_score(latitude=lat, longitude=long, return_transit_score=True)
    results.append(result)

# Extract the bike scores, walk scores, and property page links from the results
bike_scores = [result.bike_score for result in results]
walk_scores = [result.walk_score for result in results]
property_page_links = [result.property_page_link for result in results]
transit_scores = [result.transit_score for result in results]

# Add the bike scores, walk scores, and property page links to the corresponding rows of the dataframe
# missing['bike_scores'] = bike_scores
# missing['walk_scores'] = walk_scores
last_missing['transit_scores'] = transit_scores
# missing['property_page_links'] = property_page_links

In [ ]:
# check from here down

In [14]:
last_missing.shape

(807, 7)

In [15]:
last_missing.head()

,id,latitude,longitude,bike_scores,walk_scores,property_page_links,transit_scores
0,7052545,39.76662,-105.05283,65,80,https://www.walkscore.com/score/loc/lat=39.766...,37.0
1,9135545,39.76631,-105.05273,65,80,https://www.walkscore.com/score/loc/lat=39.766...,37.0
2,9445553,39.76582,-105.05254,65,80,https://www.walkscore.com/score/loc/lat=39.765...,37.0
3,9446217,39.76581,-105.05252,65,80,https://www.walkscore.com/score/loc/lat=39.765...,37.0
4,13579869,39.76786,-105.05258,65,85,https://www.walkscore.com/score/loc/lat=39.767...,37.0

In [16]:
last_missing.tail()

,id,latitude,longitude,bike_scores,walk_scores,property_page_links,transit_scores
802,633960593683726230,39.64161,-104.88049,42,7,https://www.walkscore.com/score/loc/lat=39.641...,NaN
803,711842136992485364,39.69743,-104.92800,85,24,https://www.walkscore.com/score/loc/lat=39.697...,NaN
804,695599039867813661,39.79158,-105.02502,44,72,https://www.walkscore.com/score/loc/lat=39.791...,NaN
805,744879475381056951,39.79178,-105.03394,43,60,https://www.walkscore.com/score/loc/lat=39.791...,NaN
806,780774986367626549,39.67400,-104.87516,64,70,https://www.walkscore.com/score/loc/lat=39.674...,NaN

In [17]:
last_missing.isna().sum()

id                      0
latitude                0
longitude               0
bike_scores             0
walk_scores             0
property_page_links     0
transit_scores         11
dtype: int64

In [18]:
no_longer_missing= last_missing[last_missing['transit_scores'].notna()]

In [20]:
no_longer_missing.shape

(796, 7)

In [21]:
last_11 = last_missing[last_missing['transit_scores'].isna()]
last_11.shape

(11, 7)

In [23]:
so_close=pd.concat([one_to_go, no_longer_missing])

In [24]:
so_close.head()

,id,latitude,longitude,bike_scores,walk_scores,property_page_links,transit_scores
0,177,39.69551,-104.92489,84,51,https://www.walkscore.com/score/loc/lat=39.695...,37.0
1,360,39.76758,-105.00316,93,90,https://www.walkscore.com/score/loc/lat=39.767...,49.0
2,2361919,39.77960,-105.03859,76,81,https://www.walkscore.com/score/loc/lat=39.779...,34.0
3,2386289,39.76777,-105.03529,75,86,https://www.walkscore.com/score/loc/lat=39.767...,39.0
4,4992412,39.76822,-105.00249,93,90,https://www.walkscore.com/score/loc/lat=39.768...,49.0

In [25]:
so_close.shape

(5225, 7)

In [26]:
so_close.isna().sum()

id                     0
latitude               0
longitude              0
bike_scores            0
walk_scores            0
property_page_links    0
transit_scores         0
dtype: int64

In [27]:
so_close.to_csv('../data/so_close.csv')

In [28]:
last_11.head()

,id,latitude,longitude,bike_scores,walk_scores,property_page_links,transit_scores
7,15125534,39.69714,-104.92788,85,24,https://www.walkscore.com/score/loc/lat=39.697...,NaN
9,27128420,39.66106,-104.91274,72,62,https://www.walkscore.com/score/loc/lat=39.661...,NaN
88,49113893,39.79160,-105.03085,43,54,https://www.walkscore.com/score/loc/lat=39.791...,NaN
239,50937152,39.65144,-105.05875,51,14,https://www.walkscore.com/score/loc/lat=39.651...,NaN
800,54295048,39.79167,-105.03103,43,54,https://www.walkscore.com/score/loc/lat=39.791...,NaN

In [29]:
last_11=last_11.drop('transit_scores', axis=1)

In [30]:
last_11

,id,latitude,longitude,bike_scores,walk_scores,property_page_links
7,15125534,39.69714,-104.92788,85,24,https://www.walkscore.com/score/loc/lat=39.697...
9,27128420,39.66106,-104.91274,72,62,https://www.walkscore.com/score/loc/lat=39.661...
88,49113893,39.79160,-105.03085,43,54,https://www.walkscore.com/score/loc/lat=39.791...
239,50937152,39.65144,-105.05875,51,14,https://www.walkscore.com/score/loc/lat=39.651...
800,54295048,39.79167,-105.03103,43,54,https://www.walkscore.com/score/loc/lat=39.791...
801,574647260876853318,39.70299,-104.93342,88,83,https://www.walkscore.com/score/loc/lat=39.702...
802,633960593683726230,39.64161,-104.88049,42,7,https://www.walkscore.com/score/loc/lat=39.641...
803,711842136992485364,39.69743,-104.92800,85,24,https://www.walkscore.com/score/loc/lat=39.697...
804,695599039867813661,39.79158,-105.02502,44,72,https://www.walkscore.com/score/loc/lat=39.791...
805,744879475381056951,39.79178,-105.03394,43,60,https://www.walkscore.com/score/loc/lat=39.791...
806,780774986367626549,39.67400,-104.87516,64,70,https://www.walkscore.com/score/loc/lat=39.674...

In [31]:
api_key = 'bfbd763410626e5d278b9430e7d89c3e'

walkscore_api = WalkScoreAPI(api_key = api_key)

# Extract the latitude and longitude values
latitudes = last_11['latitude']
longitudes = last_11['longitude']

# Make API requests to get the walk scores, bike scores, and property page links
results = []
for lat, long in zip(latitudes, longitudes):
    result = walkscore_api.get_score(latitude=lat, longitude=long, return_transit_score=True)
    results.append(result)

# Extract the bike scores, walk scores, and property page links from the results
bike_scores = [result.bike_score for result in results]
walk_scores = [result.walk_score for result in results]
property_page_links = [result.property_page_link for result in results]
transit_scores = [result.transit_score for result in results]

# Add the bike scores, walk scores, and property page links to the corresponding rows of the dataframe
# missing['bike_scores'] = bike_scores
# missing['walk_scores'] = walk_scores
last_11['transit_scores'] = transit_scores
# missing['property_page_links'] = property_page_links

In [32]:
last_11.isna().sum()

id                      0
latitude                0
longitude               0
bike_scores             0
walk_scores             0
property_page_links     0
transit_scores         11
dtype: int64

In [46]:
last_11['transit_scores']=round((last_11['bike_scores']+last_11['walk_scores'])/3,1)

In [47]:
last_11.isna().sum()

id                     0
latitude               0
longitude              0
bike_scores            0
walk_scores            0
property_page_links    0
transit_scores         0
dtype: int64

In [48]:
last_11.head()

,id,latitude,longitude,bike_scores,walk_scores,property_page_links,transit_scores
7,15125534,39.69714,-104.92788,85,24,https://www.walkscore.com/score/loc/lat=39.697...,36.3
9,27128420,39.66106,-104.91274,72,62,https://www.walkscore.com/score/loc/lat=39.661...,44.7
88,49113893,39.79160,-105.03085,43,54,https://www.walkscore.com/score/loc/lat=39.791...,32.3
239,50937152,39.65144,-105.05875,51,14,https://www.walkscore.com/score/loc/lat=39.651...,21.7
800,54295048,39.79167,-105.03103,43,54,https://www.walkscore.com/score/loc/lat=39.791...,32.3

In [49]:
so_close=pd.read_csv('../data/so_close.csv')

In [51]:
so_close.head()

,Unnamed: 0,id,latitude,longitude,bike_scores,walk_scores,property_page_links,transit_scores
0,0,177,39.69551,-104.92489,84,51,https://www.walkscore.com/score/loc/lat=39.695...,37.0
1,1,360,39.76758,-105.00316,93,90,https://www.walkscore.com/score/loc/lat=39.767...,49.0
2,2,2361919,39.77960,-105.03859,76,81,https://www.walkscore.com/score/loc/lat=39.779...,34.0
3,3,2386289,39.76777,-105.03529,75,86,https://www.walkscore.com/score/loc/lat=39.767...,39.0
4,4,4992412,39.76822,-105.00249,93,90,https://www.walkscore.com/score/loc/lat=39.768...,49.0

In [52]:
so_close=so_close.drop('Unnamed: 0', axis=1)

In [8]:
one_to_go.head()

,Unnamed: 0,id,latitude,longitude,bike_scores,walk_scores,property_page_links,transit_scores
0,0,177,39.69551,-104.92489,84,51,https://www.walkscore.com/score/loc/lat=39.695...,37.0
1,1,360,39.76758,-105.00316,93,90,https://www.walkscore.com/score/loc/lat=39.767...,49.0
2,2,2361919,39.77960,-105.03859,76,81,https://www.walkscore.com/score/loc/lat=39.779...,34.0
3,3,2386289,39.76777,-105.03529,75,86,https://www.walkscore.com/score/loc/lat=39.767...,39.0
4,4,4992412,39.76822,-105.00249,93,90,https://www.walkscore.com/score/loc/lat=39.768...,49.0

In [53]:
done=pd.concat([so_close, last_11])

In [54]:
done.shape

(5236, 7)

In [55]:
done.isna().sum()

id                     0
latitude               0
longitude              0
bike_scores            0
walk_scores            0
property_page_links    0
transit_scores         0
dtype: int64

In [56]:
# done.to_csv('../data/completed_api.csv')

In [ ]:
39.76639

In [82]:
result = walkscore_api.get_score(latitude = 39.76639, longitude = -104.97145, return_transit_score=True)

# the WalkScore for the location
result.walk_score

93

In [83]:
result.walk_description

"Walker's Paradise"

In [84]:
# the TransitScore for the location
result.transit_score

#according to forums online, the transit score isn't included with the stanard API...

57

In [85]:
# the BikeScore for the location
result.bike_score

98

In [86]:
missing['property_page_links'] = property_page_links

NameError: name 'missing' is not defined

In [87]:
result.property_page_link

'https://www.walkscore.com/score/loc/lat=39.76639/lng=-104.97145/?utm_source=carlhorwitz.github.io&utm_medium=ws_api&utm_campaign=ws_api'

In [78]:


wtf = pd.read_csv('../data/mergedAPI2.csv')
wtf.head(2)

,id,latitude,longitude,price,shared_status,accommodates,accomodation_group,bathrooms,bedrooms,beds_adjusted,neighborhood,has_neighborhood_overview,has_reviews,listing_url,host_in_CO,host_lives_in_neighborhood,host_id,host_name,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,host_total_listings_count,host_has_profile_pic,host_identity_verified,has_host_about,years_hosting,years_of_reviews,license_listed,response_time,host_lives_in_neighborhood.1,name,host_about,description,neighborhood_overview,amenities,minimum_nights,maximum_nights,min_stay_group,max_stay_group,has_availability,instant_bookable,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month,bike_scores,walk_scores,property_page_links,transit_scores
0,177,39.69551,-104.92489,$79.00,entire home,2,0-2,1.0,1.0,1.0,Virginia Village,1,1,https://www.airbnb.com/rooms/177,1,1,615,Joe,within an hour,1.0,1.00,1.0,Virginia Village,2.0,2.0,1.0,0.0,1,15.0,6.0,1,0.0,1,Tiny Home in the Heart of the City- ECO FRIENDLY,"I'm originally from Oklahoma, but have lived i...","160 sq ft + 80 sq ft loft for sleeping, Sleeps...","Quiet neighborhood next to park, creeks and bi...","[""Hot water"", ""Long term stays allowed"", ""Coff...",29,400,month,long_term,1,0,120,24,0,4.85,4.96,4.89,4.97,4.94,4.85,4.78,1.56,84.0,51.0,https://www.walkscore.com/score/loc/lat=39.695...,37.0
1,360,39.76758,-105.00316,$133.00,entire home,3,3-4,1.0,2.0,2.0,Highland,1,1,https://www.airbnb.com/rooms/360,1,1,666,Jennifer & Giovanni,within an hour,1.0,0.87,1.0,Highland,4.0,4.0,1.0,1.0,1,15.0,4.0,1,0.0,1,Sit in the Peaceful Garden of the Chickadee Co...,We are artists and tinkerers.\r\n \r\nWe enjoy...,Enjoy the famous Colorado weather and unplug i...,The cottage is located in the center of Lower ...,"[""Coffee maker"", ""Washer"", ""Bedroom comforts"",...",29,35,month,2_months,1,0,174,7,1,4.99,4.99,4.96,5.00,5.00,5.00,4.91,3.26,93.0,90.0,https://www.walkscore.com/score/loc/lat=39.767...,49.0

In [79]:
wtf[wtf['transit_scores'].isna()].head()

,id,latitude,longitude,price,shared_status,accommodates,accomodation_group,bathrooms,bedrooms,beds_adjusted,neighborhood,has_neighborhood_overview,has_reviews,listing_url,host_in_CO,host_lives_in_neighborhood,host_id,host_name,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,host_total_listings_count,host_has_profile_pic,host_identity_verified,has_host_about,years_hosting,years_of_reviews,license_listed,response_time,host_lives_in_neighborhood.1,name,host_about,description,neighborhood_overview,amenities,minimum_nights,maximum_nights,min_stay_group,max_stay_group,has_availability,instant_bookable,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month,bike_scores,walk_scores,property_page_links,transit_scores
503,16244480,39.74874,-105.03931,"$2,000.00",entire home,6,5-6,3.5,4.0,4.0,Sloan Lake,1,1,https://www.airbnb.com/rooms/16244480,1,0,4156700,James,within an hour,1.0,0.88,1.0,Sloane Lake,3.0,3.0,1.0,1.0,1,11.0,6.0,1,0.0,0,Luxury in the Highlands - Huge home with elevator,I am an airline pilot and part-time military c...,"Nicely decorated, well furnished home in Denve...",Sloans Lake / Highalnds is Denver's hottest ne...,"[""Long term stays allowed"", ""Coffee maker"", ""W...",1,1125,weekend,long_term,1,0,6,1,0,5.0,5.0,4.83,5.0,5.0,5.0,5.0,0.08,NaN,NaN,NaN,NaN
1751,41877877,39.76828,-104.97083,"$2,399.00",entire home,7,6-7,2.5,3.0,4.0,Cole,1,1,https://www.airbnb.com/rooms/41877877,1,1,45397806,Joshua,within an hour,1.0,1.00,0.0,Cole,1.0,1.0,1.0,1.0,1,8.0,2.0,1,0.0,1,NEW SPACIOUS 3BR ROOFTOP VIEWS RIGHT NEXT TO R...,Entrepreneur enjoying life one day at a time,BRAND NEW build/listing just 2 blocks from RiN...,Over 25+ breweries and restaurants within a 1....,"[""Hot water"", ""Long term stays allowed"", ""Coff...",3,90,weekend,3_months,1,0,17,3,0,5.0,5.0,4.88,5.0,5.0,5.0,5.0,0.50,NaN,NaN,NaN,NaN
1767,40863840,39.76725,-105.00466,"$9,999.00",hotel Room,8,6-7,2.0,2.0,7.0,Highland,1,0,https://www.airbnb.com/rooms/40863840,1,1,312409268,"Life House, Lower Highlands",within an hour,1.0,1.00,0.0,Highland,8.0,8.0,1.0,1.0,1,4.0,0.0,1,0.0,1,Victorian Suite in a Locally-Rooted Boutique H...,"Welcome home to your western homestead, where ...",The Victorian Suite feels as spacious as the v...,"Lower Highlands, or LoHi for short, once overl...","[""First aid kit"", ""Private entrance"", ""Long te...",29,1125,month,long_term,1,1,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2089,45803041,39.73936,-104.89445,"$4,500.00",private room,2,0-2,1.0,1.0,1.0,East Colfax,1,1,https://www.airbnb.com/rooms/45803041,1,0,370987920,Daniel,NaN,NaN,NaN,0.0,NaN,1.0,2.0,1.0,1.0,0,3.0,0.0,0,4.0,0,Escape to Denver King stile,NaN,people are allowed to use all comon airreas ki...,very quiet here and everyone pretty much Minds...,"[""Hot water"", ""Bed linens"", ""Conditioner"", ""Po...",29,60,month,2_months,1,0,1,0,0,5.0,5.0,4.00,5.0,5.0,5.0,5.0,0.04,NaN,NaN,NaN,NaN
2117,45518735,39.72520,-104.95734,"$4,950.00",entire home,8,6-7,4.5,4.0,4.0,Cherry Creek,0,0,https://www.airbnb.com/rooms/45518735,1,1,264336356,Carolyn,NaN,NaN,NaN,0.0,Cherry Creek,1.0,2.0,1.0,1.0,0,4.0,0.0,0,4.0,1,Gorgeous Cherry Creek Townhome!,NaN,FULLY FURNISHED luxury townhome in the heart o...,NaN,"[""Private entrance"", ""Long term stays allowed""...",30,1125,month,long_term,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [80]:
wtf.loc[3444, ['walk_scores', 'bike_scores', 'property_page_links', 'transit_scores']] = [99.0, 94.0, 'https://www.walkscore.com/score/loc/lat=39.76154/lng=-104.97725/?utm_source=carlhorwitz.github.io&utm_medium=ws_api&utm_campaign=ws_api', 59.0]

In [90]:
wtf.loc[3862, ['walk_scores', 'bike_scores', 'property_page_links', 'transit_scores']] = [93.0, 98.0, 'https://www.walkscore.com/score/loc/lat=39.76639/lng=-104.97145/?utm_source=carlhorwitz.github.io&utm_medium=ws_api&utm_campaign=ws_api', 57.0]

In [91]:
wtf.loc[3862]

id                                                             610376216212666481
latitude                                                                 39.76639
longitude                                                              -104.97145
price                                                                     $101.00
shared_status                                                         entire home
accommodates                                                                    2
accomodation_group                                                            0-2
bathrooms                                                                     1.0
bedrooms                                                                      1.0
beds_adjusted                                                                 1.0
neighborhood                                                                 Cole
has_neighborhood_overview                                                       0
has_reviews                                                                     1
listing_url                       https://www.airbnb.com/rooms/610376216212666481
host_in_CO                                                                      1
host_lives_in_neighborhood                                                      1
host_id                                                                  27848578
host_name                                                                   Kayla
host_response_time                                                 within an hour
host_response_rate                                                            1.0
host_acceptance_rate                                                          1.0
host_is_superhost                                                             0.0
host_neighbourhood                                                           Cole
host_listings_count                                                           2.0
host_total_listings_count                                                     2.0
host_has_profile_pic                                                          1.0
host_identity_verified                                                        1.0
has_host_about                                                                  0
years_hosting                                                                 8.0
years_of_reviews                                                              0.0
license_listed                                                                  0
response_time                                                                 0.0
host_lives_in_neighborhood.1                                                    1
name                                       Historic RINO home | Walk to the train
host_about                                                                    NaN
description                     Our historic Denver town home is 3 blocks (0.3...
neighborhood_overview                                                         NaN
amenities                       ["Cleaning products", "Hot water", "Long term ...
minimum_nights                                                                 29
maximum_nights                                                                 95
min_stay_group                                                              month
max_stay_group                                                           6_months
has_availability                                                                1
instant_bookable                                                                0
number_of_reviews                                                               2
number_of_reviews_ltm                                                           2
number_of_reviews_l30d                                                          1
review_scores_rating                                                          5.0
review_scores_accuracy                                                        4.5
review_scores_cleanliness                                                     4.5
review_scores_checkin                                                         5.0
review_scores_communication                                                   5.0
review_scores_location                                                        5.0
review_scores_value                                                           5.0
reviews_per_month                                                            0.49
bike_scores                                                                  98.0
walk_scores                                                                  93.0
property_page_links             https://www.walkscore.com/score/loc/lat=39.766...
transit_scores                                                               57.0
Name: 3862, dtype: object

In [92]:
wtf.isna().sum()

id                                 0
latitude                           0
longitude                          0
price                              0
shared_status                      0
accommodates                       0
accomodation_group                 0
bathrooms                          0
bedrooms                           0
beds_adjusted                      0
neighborhood                       0
has_neighborhood_overview          0
has_reviews                        0
listing_url                        0
host_in_CO                         0
host_lives_in_neighborhood         0
host_id                            0
host_name                          0
host_response_time               734
host_response_rate               734
host_acceptance_rate             429
host_is_superhost                  0
host_neighbourhood               304
host_listings_count                0
host_total_listings_count          0
host_has_profile_pic               0
host_identity_verified             0
has_host_about                     0
years_hosting                      0
years_of_reviews                   0
license_listed                     0
response_time                      0
host_lives_in_neighborhood.1       0
name                               0
host_about                      1994
description                       23
neighborhood_overview           1519
amenities                          0
minimum_nights                     0
maximum_nights                     0
min_stay_group                     0
max_stay_group                     0
has_availability                   0
instant_bookable                   0
number_of_reviews                  0
number_of_reviews_ltm              0
number_of_reviews_l30d             0
review_scores_rating             898
review_scores_accuracy           902
review_scores_cleanliness        902
review_scores_checkin            902
review_scores_communication      902
review_scores_location           902
review_scores_value              902
reviews_per_month                898
bike_scores                       12
walk_scores                       12
property_page_links               12
transit_scores                    12
dtype: int64

In [93]:
wtf.to_csv('../data/mergedAPI2.csv')